### PR TITLE
Arbor/v0.2.0

### PR DESCRIPTION
**Pull request by narendasan**
Updated Arbor to v0.2.0 which should mean we only need to import arbor instead of 3 different packages. corresponding changes needed in the api gateway should be here. Has been tested with a couple of the services and client.

### CODE REVIEW

**Comment by bcongdon** [comment]
Can you add the import/install changes to the Dockerfile? (https://github.com/acm-uiuc/groot-api-gateway/blob/fe97bd2b5c6f3cf26609a89287813f875bb63eb0/Dockerfile#L15)

**Comment by narendasan** [comment]
Forgot to push the changes, such be up to date now

**Comment by narendasan** [comment]
Added building the docker container to travis, should catch issues like this in the future

**Comment by bcongdon** [comment]
Now that Arbor is becoming more mature, we might want to start tagging releases.

**Comment by narendasan** [comment]
Yeah, I have started to do that, this is going to be v0.2.0 once the release tasks are done (mostly documentation at this point). v0.1.0 is what the api-gateway master is running off of. I am also looking at dependency management

**Comment by narendasan** [comment]
Realized that there is a bunch of stuff I need to fix in arbor before is goes in, but this code should be pretty much stable

**Comment by narendasan** [comment]
Ok things should work now. I have added dependency management using ```dep``` (the go dependency manager) and it should track arbor and its dependencies. It should only be enforced in docker though since working with ```dep``` outside the go workspace is a bit odd. The build script will still be the preferred method for building changes in dev.  The build script should also now get and install for you so, the first time set up stuff is no longer relevant. There were also a couple API changes (basically all the gateway cares about is now having to specify port).

**Pull request merged**
